server {
    listen 8080;
    server_name localhost;
    root /home/mipinhei/Desktop/Common_Core/webserv_git/www;
    client_max_body_size 1M;

    error_page 404 /errorPages/404NotFound.html;

    location / {
        root /home/mipinhei/Desktop/Common_Core/webserv_git/www;
        allow_methods GET;
        autoindex on;
    }

    location /upload {
        allow_methods POST DELETE;
        upload_store /home/mipinhei/Desktop/Common_Core/webserv_git/www/uploads;
    }
}
