server {
    listen 8080;
    root ./www/html;
    server_name site1.com;
    client_max_body_size 5M;

    location / {
        root ./www/html;
        allow_methods GET;
    }
}

server {
    listen 9090;
    root ./www/html;
    server_name site2.com;
    client_max_body_size 2M;

    location / {
        root ./www/html;
        allow_methods GET;
    }
}