server {
	root www/html;
	listen localhost:9090;
	server_name localhost;
	client_max_body_size 200M;
	index index.html;

	location / {
		allow_methods GET;
		autoindex off;
	}

	location /post_body {
		allow_methods POST GET DELETE;
		client_max_body_size 100;
	}

	location /directory {
		allow_methods GET POST;
		alias YoupiBanane;
		autoindex off;
		index youpi.bad_extension;
		cgi_pass .bla ./cgi_tester;
	}

	location /cgi-bin {
		allow_methods GET POST;
		alias www/cgi-bin;
		cgi_pass .py /usr/bin/python3;
	}
}